#!/bin/bash
#SBATCH --qos=12c-1h_2gpu
#SBATCH -o gamd_test_95D.output
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
##SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --cpus-per-task=1
##SBATCH --requeue
#SBATCH -J gamd_test_95D

##------------------------------------------------------------------------------

echo "CUDA_DEVICE=/dev/nvidia$CUDA_VISIBLE_DEVICES"
#module load cuda/10.1_cudnn-7.6.2
#module load namd/2.11-gcc-cuda
module load namd/2.13
setenv LD_LIBRARY_PATH ".:$LD_LIBRARY_PATH"
namd2 +p12 +idlepoll +isomalloc_sync gamd_test_95D.inp > gamd_test_95D.log
